### ISSUE TITLE
multiblocks related issue

### ISSUE THREAD

**Issue by Zafaranec** [Cassiobsk8/Industrial_Renewal#113]
**Versions:**
-Minecraft Forge: 14.23.5.2854
-Industrial Renewal: 0.21.4

**What happens:**

Crash or strange behavior, when you place multiblocks from 0.20 and 0.21 like storage rack, place another on top, brake bottom one... that's it, tank and battery bank disappear content, storage rack cause crash

**What should happen:**

works I think, or maybe not crash at least please

I'm huge fan of your mod and appreciate your hard job...

**Comment by Cassiobsk8** [comment]
Can you send the crash log?

**Comment by Zafaranec** [comment]
Sure, I have actually two different:

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 225, Size: 135
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 225, Size: 135
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.inventory.Container.getSlot(Container.java:120)
    at net.minecraft.inventory.Container.putStackInSlot(Container.java:519)
    at net.minecraft.client.network.NetHandlerPlayClient.handleSetSlot(NetHandlerPlayClient.java:1154)
    at net.minecraft.network.play.server.SPacketSetSlot.processPacket(SourceFile:30)
    at net.minecraft.network.play.server.SPacketSetSlot.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

and

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at cassiokf.industrialrenewal.gui.container.ContainerStorageChest.<init>(ContainerStorageChest.java:13)
    at cassiokf.industrialrenewal.init.GUIHandler.getServerGuiElement(GUIHandler.java:92)
    at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at cassiokf.industrialrenewal.tileentity.TEStorageChest.openGui(TEStorageChest.java:74)
    at cassiokf.industrialrenewal.blocks.BlockStorageChest.onBlockActivated(BlockStorageChest.java:34)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
