### ISSUE TITLE
Crash When opening a world.

### ISSUE THREAD

**Issue by thiago1255** [Cassiobsk8/Industrial_Renewal#99]
Hello ! I love playing minecraft with your mod. But when I open a world. The game fails.
(started to happen when I updated the mod)
Minecraft Version: 1.12.2
Mod Version: 0.18.0
Forge Version: 14.23.5.2847

I tried to access two worlds, each involved a different error, related to the mod:
[crash-2020-08-30_15.01.04-server.txt](https://github.com/Cassiobsk8/Industrial_Renewal/files/5147250/crash-2020-08-30_15.01.04-server.txt)
[crash-2020-08-30_14.46.38-server.txt](https://github.com/Cassiobsk8/Industrial_Renewal/files/5147251/crash-2020-08-30_14.46.38-server.txt)

**Comment by Zafaranec** [comment]
same problem, crash after placed Gutter
 
stacktrace:

Description: Ticking block entity

java.lang.NullPointerException
    at cassiokf.industrialrenewal.tileentity.TileEntityGutter.checkForOutPuts(TileEntityGutter.java:96)
    at cassiokf.industrialrenewal.tileentity.tubes.TileEntityMultiBlocksTube.initializeMultiblockIfNecessary(TileEntityMultiBlocksTube.java:102)
    at cassiokf.industrialrenewal.tileentity.tubes.TileEntityMultiBlocksTube.initializeMultiblockIfNecessary(TileEntityMultiBlocksTube.java:66)
    at cassiokf.industrialrenewal.tileentity.tubes.TileEntityMultiBlocksTube.update(TileEntityMultiBlocksTube.java:44)

**Comment by thiago1255** [comment]
Now with the update it returned to working normally. Thank you !
